"""empty message

Revision ID: d43ab8999a19
Revises:
Create Date: 2026-02-28 17:07:42.775096

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d43ab8999a19"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("level_land", sa.Integer(), nullable=False),
        sa.Column("level_sea", sa.Integer(), nullable=False),
        sa.Column(
            "character_class",
            sa.Enum(
                "MERCENARY",
                "EXPLORER",
                "NOBLE",
                "SAINT",
                "GLADIATOR",
                "GUARDIAN_SWORDSMAN",
                "EXCAVATOR",
                "SNIPER",
                "COURT_MAGICIAN",
                "MAGIC_KNIGHT",
                "PRIEST",
                "SHAMAN",
                name="characterclass",
            ),
            nullable=False,
        ),
        sa.Column("is_female", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_player_is_active", "player", ["is_active", "name"], unique=False
    )
    op.create_table(
        "round_match_team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "season",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_running", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "player_season_stats",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("elo", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "season_id"),
    )
    op.create_table(
        "round",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "ONE_VS_ONE",
                "TWO_VS_TWO",
                "THREE_VS_THREE",
                "FOUR_VS_FOUR",
                "FIVE_VS_FIVE",
                "SIX_VS_SIX",
                name="roundmode",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "RUNNING", "COMPLETED", name="roundstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "round_match_participant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("level_land", sa.Integer(), nullable=False),
        sa.Column("level_sea", sa.Integer(), nullable=False),
        sa.Column(
            "character_class",
            sa.Enum(
                "MERCENARY",
                "EXPLORER",
                "NOBLE",
                "SAINT",
                "GLADIATOR",
                "GUARDIAN_SWORDSMAN",
                "EXCAVATOR",
                "SNIPER",
                "COURT_MAGICIAN",
                "MAGIC_KNIGHT",
                "PRIEST",
                "SHAMAN",
                name="characterclass",
            ),
            nullable=False,
        ),
        sa.Column("is_female", sa.Boolean(), nullable=False),
        sa.Column("elo_before", sa.Integer(), nullable=True),
        sa.Column("elo_change", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["round_match_team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "round_match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("team_1_id", sa.Integer(), nullable=False),
        sa.Column("team_2_id", sa.Integer(), nullable=False),
        sa.Column(
            "match_result",
            sa.Enum(
                "UNSET",
                "CANCELED",
                "WIN_TEAM_1",
                "WIN_TEAM_2",
                "DRAW",
                name="matchresult",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["round.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_1_id"],
            ["round_match_team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_2_id"],
            ["round_match_team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "round_participant",
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["round.id"],
        ),
        sa.PrimaryKeyConstraint("round_id", "player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("round_participant")
    op.drop_table("round_match")
    op.drop_table("round_match_participant")
    op.drop_table("round")
    op.drop_table("player_season_stats")
    op.drop_table("user")
    op.drop_table("season")
    op.drop_table("round_match_team")
    op.drop_index("ix_player_is_active", table_name="player")
    op.drop_table("player")
    # ### end Alembic commands ###
