"""empty message

Revision ID: d983b3c607c3
Revises: d43ab8999a19
Create Date: 2026-03-01 14:39:41.834820

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d983b3c607c3"
down_revision: Union[str, Sequence[str], None] = "d43ab8999a19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("season", sa.Column("description", sa.String(), nullable=True))

    op.execute("UPDATE season SET description = 'default description'")

    op.alter_column("season", "description", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("season", "description")
    # ### end Alembic commands ###
