/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeasonsIdRouteImport } from './routes/seasons/$id'
import { Route as RoundsIdRouteImport } from './routes/rounds/$id'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUpdatePlayersRouteImport } from './routes/admin/update-players'
import { Route as AdminSeasonsRouteImport } from './routes/admin/seasons'
import { Route as AdminRoundsRouteImport } from './routes/admin/rounds'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsIdRoute = SeasonsIdRouteImport.update({
  id: '/seasons/$id',
  path: '/seasons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsIdRoute = RoundsIdRouteImport.update({
  id: '/rounds/$id',
  path: '/rounds/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdatePlayersRoute = AdminUpdatePlayersRouteImport.update({
  id: '/admin/update-players',
  path: '/admin/update-players',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeasonsRoute = AdminSeasonsRouteImport.update({
  id: '/admin/seasons',
  path: '/admin/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoundsRoute = AdminRoundsRouteImport.update({
  id: '/admin/rounds',
  path: '/admin/rounds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/admin/rounds': typeof AdminRoundsRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/update-players': typeof AdminUpdatePlayersRoute
  '/auth/login': typeof AuthLoginRoute
  '/rounds/$id': typeof RoundsIdRoute
  '/seasons/$id': typeof SeasonsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/admin/rounds': typeof AdminRoundsRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/update-players': typeof AdminUpdatePlayersRoute
  '/auth/login': typeof AuthLoginRoute
  '/rounds/$id': typeof RoundsIdRoute
  '/seasons/$id': typeof SeasonsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/admin/rounds': typeof AdminRoundsRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/update-players': typeof AdminUpdatePlayersRoute
  '/auth/login': typeof AuthLoginRoute
  '/rounds/$id': typeof RoundsIdRoute
  '/seasons/$id': typeof SeasonsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/imprint'
    | '/privacy'
    | '/rules'
    | '/admin/rounds'
    | '/admin/seasons'
    | '/admin/update-players'
    | '/auth/login'
    | '/rounds/$id'
    | '/seasons/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/imprint'
    | '/privacy'
    | '/rules'
    | '/admin/rounds'
    | '/admin/seasons'
    | '/admin/update-players'
    | '/auth/login'
    | '/rounds/$id'
    | '/seasons/$id'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/imprint'
    | '/privacy'
    | '/rules'
    | '/admin/rounds'
    | '/admin/seasons'
    | '/admin/update-players'
    | '/auth/login'
    | '/rounds/$id'
    | '/seasons/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  RulesRoute: typeof RulesRoute
  AdminRoundsRoute: typeof AdminRoundsRoute
  AdminSeasonsRoute: typeof AdminSeasonsRoute
  AdminUpdatePlayersRoute: typeof AdminUpdatePlayersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  RoundsIdRoute: typeof RoundsIdRoute
  SeasonsIdRoute: typeof SeasonsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$id': {
      id: '/seasons/$id'
      path: '/seasons/$id'
      fullPath: '/seasons/$id'
      preLoaderRoute: typeof SeasonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds/$id': {
      id: '/rounds/$id'
      path: '/rounds/$id'
      fullPath: '/rounds/$id'
      preLoaderRoute: typeof RoundsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/update-players': {
      id: '/admin/update-players'
      path: '/admin/update-players'
      fullPath: '/admin/update-players'
      preLoaderRoute: typeof AdminUpdatePlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seasons': {
      id: '/admin/seasons'
      path: '/admin/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AdminSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rounds': {
      id: '/admin/rounds'
      path: '/admin/rounds'
      fullPath: '/admin/rounds'
      preLoaderRoute: typeof AdminRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  RulesRoute: RulesRoute,
  AdminRoundsRoute: AdminRoundsRoute,
  AdminSeasonsRoute: AdminSeasonsRoute,
  AdminUpdatePlayersRoute: AdminUpdatePlayersRoute,
  AuthLoginRoute: AuthLoginRoute,
  RoundsIdRoute: RoundsIdRoute,
  SeasonsIdRoute: SeasonsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
